# Load aliases
source ~/.dotfiles/src/zsh/aliases.zsh

# Load starship prompt
eval "$(starship init zsh)"

# Configure Heroku
export HEROKU_ORGANIZATION=seventeen-fifteen-labs

# Load Homebrew shell completion
# https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi
