# http://zanshin.net/2013/02/02/zsh-configuration-from-the-ground-up/

export PATH="/usr/local/bin:$PATH"
export PATH="$(brew --prefix homebrew/php/php71)/bin:$PATH"

# export PATH="$HOME/.rbenv/bin:/usr/local/sbin:/usr/bin:/usr/local/bin:$PATH"

export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

source ~/.zsh/plugins.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/history.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/setopt.zsh
source ~/.zsh/bindings.zsh
source ~/.zsh/autosrc.zsh

# Credentials files aren't part of the repo
[ -f ~/.zsh/credentials.zsh ] && source ~/.zsh/credentials.zsh

# added by travis gem
[ -f /Users/rogerhutchings/.travis/travis.sh ] && source /Users/rogerhutchings/.travis/travis.sh
