# http://zanshin.net/2013/02/02/zsh-configuration-from-the-ground-up/

source ~/.zsh/plugins.zsh
source ~/.zsh/history.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/setopt.zsh
source ~/.zsh/bindings.zsh
